version: '3'

services:
  cassandra:
    image: cassandra:latest  
    restart: always
    ports:
      - "9042:9042"  
    container_name: cassandra  
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
    driver: local

